name: Release bleeding edge image
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - ao3_rss/**
      - Dockerfile
      - requirements.txt

jobs:
  build-and-push-edge-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/ao3-rss:edge
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build container image (Alpine)
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          platforms: linux/amd64
          file: ./Dockerfile-alpine
          tags: ghcr.io/${{ github.repository_owner }}/ao3-rss:edge-alpine
          cache-from: type=gha
          cache-to: type=gha,mode=max
