name: Release stable image
on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build-and-push-stable-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/ao3-rss:${{ steps.get_version.outputs.VERSION }}-alpine
            ghcr.io/${{ github.repository_owner }}/ao3-rss:latest-alpine
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build container image (Alpine)
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          platforms: linux/amd64
          file: ./Dockerfile-alpine
          tags: ghcr.io/${{ github.repository_owner }}/ao3-rss:edge
          cache-from: type=gha
          cache-to: type=gha,mode=max
